# Generated by Django 5.1.4 on 2024-12-06 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_rides', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='dropoff_location',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='pickup_location',
        ),
    ]
